server {
    listen 8080;
    server_name localhost;
    client_max_body_size 1000000;

    location / {
        allow_methods GET;
        root ./;
        autoindex on;
    }

    location /post_body {
        allow_methods POST;
        client_max_body_size 100;
        root ./;
    }

    location /directory {
        allow_methods GET;
        root ./YoupiBanane;
        index youpi.bad_extension;
    }

    location *.bla {
        allow_methods POST;
        root ./;
        cgi_ext .bla ./cgi_test;
    }
}